blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/blak0p/dotfiles/discussions
    about: Please use Discussions for questions, configuration ideas, or general help
