#!/usr/bin/env fish
set winfo (qdbus org.kde.KWin /KWin org.kde.KWin.queryWindowInfo 2>/dev/null)
echo $winfo | grep -q "resourceClass: kitty" || exit 0

set caption (echo $winfo | string match -r 'caption: (.+)' | string replace -r 'caption: ' '')
set session_name (echo $caption | string split ' |' | head -1 | string trim)

if test -n "$session_name"
    zellij kill "$session_name" 2>/dev/null
    sleep 0.3
end

qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut "Window Close" 2>/dev/null
