symlinks = [
  ".bashrc.d",
  ".nanorc",
  ".git-credentials",
  ".fzf.bash",
  ".bash",
  ".engram",
  ".local/state/opencode",
  ".local/share/opencode",
  ".ssh/known_hosts",
  ".claude",
  ".claude.json",
  ".secrets",
  "/var/usrlocal/bin/ollama",
  ".gemini",
  ".codex",
  ".pi",
  ".config/agent-state",
]

